In [16]:
#importing the required packages
import numpy as np
import time

In [3]:
#importing the csv and extracting first 3 row's
raw_data =np.genfromtxt("Blood_Cancer.csv",
                        delimiter=",",
                        dtype=str,max_rows=1)
print("header row",raw_data)


header row ['Age' 'Gender' '"Cancer_Type(AML' ' ALL' ' CLL)"'
 '"Treatment_Type(Chemotherapy' ' Radiation)"'
 'Bone Marrow Aspiration(Positive / Negative / Not Done)'
 'Total WBC count(/cumm)'
 'Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)'
 'Lymph Node Biopsy(Positive / Negative / Not Done)'
 'Lumbar Puncture (Spinal Tap)' 'Platelet Count( (/cumm)'
 'Treatment_Outcome' '"Genetic_Data(BCR-ABL' ' FLT3)"' 'Side_Effects'
 'Diagnosis_Result' 'Comments']


In [4]:
#importing the csv and extracting first 3 row's
raw_data =np.genfromtxt("Blood_Cancer.csv",
                        delimiter=",",
                        dtype=str,skip_header=1)
#print("header row",raw_data)
print(raw_data.shape,raw_data[:5])

(2294, 15) [['77' 'Female' 'CLL' 'Targeted Therapy' 'Not Done' '39693' 'Normal'
  'Positive' 'Negative' '324539' 'Ongoing' 'FLT3' 'Mild' 'Confirmed'
  'Critical']
 ['87' 'Female' 'Lymphoma' 'Stem Cell Transplant' 'Negative' '19989'
  'Abnormal' 'Positive' 'Negative' '23748' 'Cured' 'TP53' 'Moderate'
  'Suspected' 'Critical']
 ['82' 'Male' 'AML' 'Targeted Therapy' 'Not Done' '60567' 'Abnormal'
  'Negative' 'Negative' '166343' 'Cured' 'BCR-ABL' 'Moderate' 'Confirmed'
  'Follow-up required']
 ['90' 'Male' 'ALL' 'Stem Cell Transplant' 'Positive' '43125' 'Normal'
  'Positive' 'Not Done' '232304' 'Cured' 'FLT3' 'Mild' 'Confirmed'
  'Follow-up required']
 ['51' 'Female' 'Multiple Myeloma' 'Chemotherapy' 'Positive' '53881'
  'Normal' 'Negative' 'Negative' '329230' 'Cured' 'FLT3' 'None'
  'Confirmed' 'Stable']]


In [5]:
#extracting the non categotical (numerical) colums 
num_col =[0,5,9]
numbers_data=raw_data[:,num_col]
print("numerical data:",numbers_data.shape,numbers_data[:5])


numerical data: (2294, 3) [['77' '39693' '324539']
 ['87' '19989' '23748']
 ['82' '60567' '166343']
 ['90' '43125' '232304']
 ['51' '53881' '329230']]


In [6]:
#converting the numbrs into float valuse using for loop
numbers_data = []

for i in range(raw_data.shape[1]):
    try:
        raw_data[:, i].astype(float)
        numbers_data.append(i)
    except:
        pass

print("Numeric column indices:", numbers_data)


Numeric column indices: [0, 5, 9]


In [7]:
numbers_data = raw_data[:, numbers_data].astype(float)

In [9]:
#Statistical Operations 
mean_vals = np.mean(numbers_data, axis=0)
np.set_printoptions(precision=2, suppress=True)
print("Mean values per column:\n", mean_vals)

median_vals = np.median(numbers_data, axis=0)
print("Median values per column:\n", median_vals)

std_vals = np.std(numbers_data, axis=0)
print("Standard deviation per column:\n", std_vals)

min_vals = np.min(numbers_data, axis=0)
max_vals = np.max(numbers_data, axis=0)
print("Minimum per column:\n", min_vals)
print("Maximum per column:\n", max_vals)

sum_vals = np.sum(numbers_data, axis=0)
print("Sum per column:\n", sum_vals)

percentiles_25 = np.percentile(numbers_data, 25, axis=0)
percentiles_50 = np.percentile(numbers_data, 50, axis=0)
percentiles_75 = np.percentile(numbers_data, 75, axis=0)
print("25th percentile:\n", percentiles_25)
print("50th percentile (median):\n", percentiles_50)
print("75th percentile:\n", percentiles_75)

corr_matrix = np.corrcoef(numbers_data.T)
print("Correlation matrix:\n", corr_matrix)


Mean values per column:
 [    45.44  51148.09 208040.18]
Median values per column:
 [    45.   51793.  206592.5]
Standard deviation per column:
 [    25.81  28474.   109937.06]
Minimum per column:
 [    1.  1016. 20280.]
Maximum per column:
 [    90.  99957. 399758.]
Sum per column:
 [1.04e+05 1.17e+08 4.77e+08]
25th percentile:
 [    23.    25953.75 110823.75]
50th percentile (median):
 [    45.   51793.  206592.5]
75th percentile:
 [    68.  75837. 302447.]
Correlation matrix:
 [[ 1.   -0.01 -0.02]
 [-0.01  1.    0.01]
 [-0.02  0.01  1.  ]]


In [10]:
#categorical analysis
#average Age,WBC,Platelets count by cancer subtype:
cancer_types = raw_data[:, 2] 
unique_types = np.unique(cancer_types)

for ctype in unique_types:
    mask = cancer_types == ctype
    group_values = numbers_data[mask]
    print(ctype, np.mean(group_values, axis=0))

ALL [    46.35  51899.98 212751.62]
AML [    45.98  53357.28 204916.5 ]
CLL [    43.87  50927.17 210496.61]
CML [    45.79  50469.33 200242.81]
Lymphoma [    45.57  50324.69 203762.39]
Multiple Myeloma [    45.18  49882.54 216024.17]


In [11]:
#categorical analysis
#average Age,WBC,Platelets count by gender subtype:
cancer_types = raw_data[:, 1] 
unique_types = np.unique(cancer_types)

for ctype in unique_types:
    mask = cancer_types == ctype
    group_values = numbers_data[mask]
    print(ctype, np.mean(group_values, axis=0))

Female [    45.87  50872.51 206710.93]
Male [    45.05  51400.2  209256.25]


In [13]:
#categorical analysis
#average Age,WBC,Platelets count by Side Effects subtype:
cancer_types = raw_data[:, 12] 
unique_types = np.unique(cancer_types)

for ctype in unique_types:
    mask = cancer_types == ctype
    group_values = numbers_data[mask]
    print(ctype, np.mean(group_values, axis=0))

Mild [    46.19  50154.56 211846.11]
Moderate [    45.98  52821.32 205400.  ]
None [    44.18  50592.6  207742.94]
Severe [    45.49  51051.24 207266.54]


In [14]:
#Normalizing the data
max_vals = np.max(numbers_data, axis=1).reshape(-1, 1)
normalized = numbers_data / max_vals
print("Normalized shape:", normalized.shape)

Normalized shape: (2294, 3)


In [20]:
# saving and retriving file
np.save("numbers_data.npy", numbers_data)
loaded = np.load("numbers_data.npy")

In [18]:
#Comparision of numpytime and python time 
arr_np = numbers_data.flatten()
lst = arr_np.tolist()

start = time.time()
sum_np = np.sum(arr_np**2)
print("NumPy time:", time.time() - start)

start = time.time()
sum_list = sum([x**2 for x in lst])
print("Python list time:", time.time() - start)

NumPy time: 0.0010120868682861328
Python list time: 0.001069784164428711
